version: 2
jobs:
  build:
    docker:
      - image: golang:latest
        environment:
          GO111MODULE: 'on'
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - ci-{{ .Branch }}-{{ checksum "go.sum" }}
      - run:
          name: "Run go mod download"
          command: "go mod download"
      - run:
          name: "Download Code Climate App"
          command: |
            curl -o ../cc-test-reporter -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 &&
            chmod +x ../cc-test-reporter
      - save_cache:
          key: ci-{{ .Branch }}-{{ checksum "go.sum" }}
          paths:
            - "/go"
      - run:
          name: "Test & Upload the coverage"
          command: |
            ../cc-test-reporter before-build &&
            go test -coverprofile=c.out
            export EXIT_CODE=${?};
            ../cc-test-reporter after-build --exit-code $EXIT_CODE -t gocov --prefix github.com/hiroaki-yamamoto/${CIRCLE_PROJECT_REPONAME}
